spring:
  datasource:
    url: jdbc:h2:file:./moviedb;DB_CLOSE_ON_EXIT=FALSE
    username: ${username:test}
    password: ${password:test}
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: movie

  management:
    endpoints:
      web:
        exposure:
          include: refresh,health,info,env,configprops,loggers,metrics,beans,httptrace,mappings,threaddump,sessions
      enabled-by-default: true

omdb:
  api:
    key: ${apikey}

server:
  port: 8080


## Spring Boot Actuator Info Endpoint Customization
info:
  # static properties
  app:
    name: FlickShareService
    description: Provides Data Services for FlickShareApp

# build properties from maven
  build:
    groupId: @project.groupId@
    artifact: @project.artifactId@
    name: @project.name@
    version: @project.version@

# environment variables
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}
